import { Injectable } from '@angular/core';
import { Item } from "../interfaces/items-interface";

@Injectable({
  providedIn: 'root'
})
export class ItemsService {
  baseItems: Item[] = [
    {
      name: 'B.F. Sword',
      description: '+10 Attack Damage',
      src: '../../assets/items/base/bf-sword.png',
      id: 'ad',
      selectedAmount: 0,
      equippedAmount: 0,
      parts: [],
      wearers: [],
    },
      {
        name: 'Chain Vest',
        description: '+20 Armor',
        src: '../../assets/items/base/chain_vest.png',
        id: 'armor',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: "Giant's Belt",
        description: '+150 Health',
        src: '../../assets/items/base/giants_belt.png',
        id: 'hp',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: 'Sparring Gloves',
        description: '+5% Critical Chance +10% Dodge Chance',
        src: '../../assets/items/base/gloves.png',
        id: 'crit',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: 'Recurve Bow',
        description: '+10% Attack Speed',
        src: '../../assets/items/base/bow.png',
        id: 'as',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: 'Negatron Cloak',
        description: '+20 Magic Resist',
        src: '../../assets/items/base/negatron.png',
        id: 'mr',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: 'Needlessly Large Rod',
        description: '+20% Spell Damage',
        src: '../../assets/items/base/rod.png',
        id: 'ap',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: 'Tear of the Goddess',
        description: '+15 Starting Mana',
        src: '../../assets/items/base/tear.png',
        id: 'tear',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      },
      {
        name: 'Spatula',
        description: 'It must do something...',
        src: '../../assets/items/base/spatula.png',
        id: 'spat',
        selectedAmount: 0,
        equippedAmount: 0,
        parts: [],
        wearers: [],
      }];

  combinedItems: Item[] = [
    {
      name: "Warmog's Armor",
      description: 'Grants Health 1000 bonus Health (including components).',
      src: '../../assets/items/completed/hp+hp.png',
      id: 'warmog',
      parts: ['hp', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Rapid Firecannon",
      description: 'Increases the holder\'s Attack Range by 1 hex and grants AS 50% bonus Attack Speed (including components). The holder\'s attacks can no longer miss.',
      src: '../../assets/items/completed/2as.png',
      id: 'firecannon',
      parts: ['as', 'as'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Deathblade",
      description: 'The holder gains AD 50/75/100 ★ bonus Attack Damage (including components).',
      src: '../../assets/items/completed/ad+ad.png',
      id: 'deathblade',
      parts: ['ad', 'ad'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Giant Slayer",
      description: 'The holder\'s Abilities and attacks do 20% bonus damage. If the target has more than 1800 maximum Health, the bonus increases to 60%.',
      src: '../../assets/items/completed/giant_slayer.png',
      id: 'giant_slayer',
      parts: ['ad', 'as'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Hextech Gunblade",
      description: 'The holder\'s magic and true damage from Abilities heal them for 33% of the damage dealt. The holder also heals their lowest Health ally for the same amount.\n',
      src: '../../assets/items/completed/ap_ad.png',
      id: 'gunblade',
      parts: ['ad', 'ap'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Guardian Angel",
      description: 'Prevents the holder\'s first death, placing them in stasis instead. After 2 seconds, they return with 400 Health and shed all negative effects.\n',
      src: '../../assets/items/completed/guardian_angel.png',
      id: 'ga',
      parts: ['ad', 'armor'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Bloodthirster",
      description: 'Physical damage heals the holder for 33% of the damage dealt. Upon falling below 40% Health, the holder gains a 30% maximum Health shield that lasts up to 5 seconds.\n',
      src: '../../assets/items/completed/bloodthirster.png',
      id: 'bloodthirster',
      parts: ['ad', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Zeke's Herald",
      description: 'When combat begins, the holder and all allies within 1 hexes in the same row gain AS 30% Attack Speed for the rest of combat.\n',
      src: '../../assets/items/completed/zeke.png',
      id: 'zeke',
      parts: ['ad', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Infinity Edge",
      description: 'Grants 75% Critical Strike Chance (including components) and 10% Critical Strike Damage. Each point of Critical Strike Chance above 100% becomes +1% Critical Strike Damage.\n',
      src: '../../assets/items/completed/IE.png',
      id: 'ie',
      parts: ['ad', 'crit'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Guinsoo's Rageblade",
      description: 'Attacks grant +6% bonus Attack Speed for the rest of combat. This effect can stack any number of times.\n',
      src: '../../assets/items/completed/guinsa.png',
      id: 'guinsoo',
      parts: ['ap', 'as'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Statikk  Shiv",
      description: 'The holder gains AS 15% bonus Attack Speed. Every 3rd attack from the holder unleashes a chain lightning that bounces to 4 enemies, dealing 70 magic damage and reducing their Magic Resist by 50% for 5 seconds.\n',
      src: '../../assets/items/completed/as_tear.png',
      id: 'statikk',
      parts: ['as', 'tear'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Titan's resolve",
      description: 'When the holder attacks or takes damage, they gain 2 Attack Damage and Ability Power.\n This stacks up to 25 times, at which point the holder gains 25 Armor and Magic Resist.',
      src: '../../assets/items/completed/as+armor.png',
      id: 'titan',
      parts: ['as', 'armor'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Runaan's Hurricane",
      description: 'The holder gains AD 10 Attack Damage. The holder\'s attacks fire a bolt at another nearby enemy, dealing 75% of the holder\'s Attack Damage as physical damage.\n',
      src: '../../assets/items/completed/runaan.png',
      id: 'runaan',
      parts: ['as', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Zz'Rot Portal",
      description: 'At the start of combat, the holder taunts enemies within 4 hexes.\n' +
        'When the holder dies, a Voidspawn arises taunting nearby enemies. Voidspawns that arise from summoned units are 25% effective.',
      src: '../../assets/items/completed/hp+as.png',
      id: 'zzRot',
      parts: ['as', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Last Whisper",
      description: 'When the holder inflicts a critical hit, the target\'s Armor is reduced by 70% for 5 seconds. This effect does not stack.\n',
      src: '../../assets/items/completed/Last Whisper.png',
      id: 'lw',
      parts: ['as', 'crit'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Rabadon's Deathcap",
      description: 'Grants AP 75 bonus Ability Power (including components).\n',
      src: '../../assets/items/completed/rabadon.png',
      id: 'rabadon',
      parts: ['ap', 'ap'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Archangel's Staff",
      description: 'During combat, the holder gains AP 25 Ability Power every 5 seconds.\n',
      src: '../../assets/items/completed/archangel.png',
      id: 'archangel',
      parts: ['ap', 'tear'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Locket of the Iron Solari",
      description: 'When combat begins, the holder and all allies within 2 hexes in the same row gain a shield that blocks 300.0/350.0/400 ★ damage for 8 seconds.\n',
      src: '../../assets/items/completed/locket.png',
      id: 'locket',
      parts: ['ap', 'armor'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Ionic Spark",
      description: 'Enemies within 2 hexes have their Magic Resist reduced by 50%. When they cast an Ability, they are zapped taking magic damage equal to 200% of their maximum Mana.\n',
      src: '../../assets/items/completed/ap+mr.png',
      id: 'ionic-spark',
      parts: ['ap', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Morellonomicon",
      description: 'When the holder deals magic or true damage with their Ability, they burn the target, dealing 25% of the target\'s maximum Health as true damage over 10 seconds, and reducing healing by 50% for the duration of the burn.',
      src: '../../assets/items/completed/ap+hp.png',
      id: 'morello',
      parts: ['ap', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Jeweled Gauntlet",
      description: 'The holder\'s magic and true damage from their Ability can critically strike. The holder gains 30% bonus Critical Strike Damage and AP 10 bonus Ability Power.',
      src: '../../assets/items/completed/ap+crit.png',
      id: 'jg',
      parts: ['ap', 'crit'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Blue Buff",
      description: 'The holder gains Mana 30 Starting Mana (including components). After casting their Ability, the holder gains Mana 50 mana.\n',
      src: '../../assets/items/completed/tear+tear.png',
      id: 'blue',
      parts: ['tear', 'tear'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Frozen Heart",
      description: 'Reduces the Attack Speed of enemies within 2 hexes by 35%.\n',
      src: '../../assets/items/completed/tear+armor.png',
      id: 'fh',
      parts: ['tear', 'armor'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Chalice of Power",
      description: 'When combat begins, the holder and all allies within 1 hex in the same row gain AP 30 Ability Power for the rest of combat.\n',
      src: '../../assets/items/completed/tear+mr.png',
      id: 'chalice',
      parts: ['tear', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Redemption",
      description: 'Every 5 seconds, the holder radiates an aura to allies within 1 hex, healing them for 18% of their missing Health. Affected allies take 25% reduced damage from multi-target abilities and attacks for 5 seconds.\n',
      src: '../../assets/items/completed/tear+hp.png',
      id: 'redemption',
      parts: ['tear', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Hand of Justice",
      description: 'The holder gains both of the following:\n' +
        '- +@AD@ Attack Damage and +@SP@ Ability Power.\n' +
        '- Attacks and Abilities heal for 10% of damage dealt.\n' +
        'At the beginning of each planning phase, one of these buffs is increased to @TooltipBonus@(%).',
      src: '../../assets/items/completed/tear+crit.png',
      id: 'HoJ',
      parts: ['crit', 'tear'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Bramble Vest",
      description: 'Grants Armor 70 bonus Armor (including components). Negates bonus damage from incoming critical strikes. On being hit by an attack, deal 60.0/80.0/120 ★ magic damage to all nearby enemies (once every 2.5 seconds).\n',
      src: '../../assets/items/completed/armor+armor.png',
      id: 'bramble',
      parts: ['armor', 'armor'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Gargoyle Stoneplate",
      description: 'The holder gains Armor 18 Armor and MR 18 Magic Resist for each enemy targeting them.\n',
      src: '../../assets/items/completed/armor+mr.png',
      id: 'gargoyle',
      parts: ['armor', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Sunfire Cape",
      description: 'Every 2.5 seconds, a random enemy within 2 hexes is burned for 20% of their maximum Health as true damage over 8 seconds. Any healing they receive is reduced by 50%.\n',
      src: '../../assets/items/completed/armor+hp.png',
      id: 'sunfire',
      parts: ['armor', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Shroud of Stillness",
      description: 'When combat begins, the holder shoots a beam straight ahead that delays affected enemies\' first cast, increasing their max Mana by 35% until they cast.\n',
      src: '../../assets/items/completed/armor+crit.png',
      id: 'shroud',
      parts: ['armor', 'crit'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Dragon's Claw",
      description: 'Grants MR 200 bonus Magic Resist (including components). On being hit by magic or true damage from a casted Ability, launch a fireball at the Ability\'s caster that deals magic damage equal to 18% of their maximum Health (0.5 second cooldown).\n',
      src: '../../assets/items/completed/mr+mr.png',
      id: 'dragon_claw',
      parts: ['mr', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Zephyr",
      description: 'When combat begins, the holder summons a whirlwind on the opposite side of the arena that removes the closest enemy from combat for 5 seconds. Ignores crowd control immunity.\n',
      src: '../../assets/items/completed/mr+hp.png',
      id: 'zephyr',
      parts: ['mr', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Quicksilver",
      description: 'The holder gains AS 20% bonus Attack Speed. The holder is immune to crowd control in combat for 15 seconds.\n',
      src: '../../assets/items/completed/mr+crit.png',
      id: 'quicksilver',
      parts: ['mr', 'crit'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Banshee's Claw",
      description: 'When combat begins, the holder and all allies within 1 hex(es) in the same row gain a shield that blocks the damage and effects of the first enemy Ability, up to 600 damage.\n',
      src: '../../assets/items/completed/hp+crit.png',
      id: 'banshee_claw',
      parts: ['hp', 'crit'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Thief's Gloves",
      description: 'At the beginning of each planning phase, the holder equips 2 temporary items. Temporary items increase in power based on your player level.\n',
      src: "../../assets/items/completed/Thief's Gloves.png",
      id: 'thief_glove',
      parts: ['bow', 'bow'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Challenger Emblem",
      description: 'The holder gains the Challenger trait.\n',
      src: '../../assets/items/completed/spat+as.png',
      id: 'challenger',
      parts: ['spat', 'as'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Imperial Emblem",
      description: 'The holder gains the Imperial trait.\n',
      src: '../../assets/items/completed/spat+ad.png',
      id: 'imperial',
      parts: ['spat', 'ad'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Arcanist Emblem",
      description: 'The holder gains the Arcanist trait.',
      src: '../../assets/items/completed/Arcanist.png',
      id: 'arcanist',
      parts: ['spat', 'ap'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Academy Emblem",
      description: 'The holder gains the Academy trait.\n',
      src: '../../assets/items/completed/spat+tear.png',
      id: 'academy',
      parts: ['spat', 'tear'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Syndicate Emblem",
      description: 'The holder gains the Syndicate trait.\n',
      src: '../../assets/items/completed/Syndicate.png',
      id: 'syndicate',
      parts: ['spat', 'armor'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Chemtech Emblem",
      description: 'The holder gains the Chemtech trait.\n',
      src: '../../assets/items/completed/Chemtech.png',
      id: 'chemtech',
      parts: ['spat', 'hp'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Mutant Emblem",
      description: 'The holder gains the Mutant trait.\n',
      src: '../../assets/items/completed/spat+mr.png',
      id: 'mutant',
      parts: ['spat', 'mr'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Tactician's Crown",
      description: 'The holder\'s team gains +1 maximum team size.\n',
      src: '../../assets/items/completed/spat+spat.png',
      id: 'crown',
      parts: ['spat', 'spat'],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Clockwork Emblem",
      description: 'The holder gains the Clockwork trait.\n',
      src: '../../assets/items/completed/mechanic.png',
      id: 'clockwork',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Mercenary Emblem",
      description: 'The holder gains the Mercenary trait.\n',
      src: '../../assets/items/completed/mercenary.png',
      id: 'mercenary',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Socialite Emblem",
      description: 'The holder gains the Socialite trait.\n',
      src: '../../assets/items/completed/socialite.png',
      id: 'socialite',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Enforcer Emblem",
      description: 'The holder gains the Enforcer trait.\n',
      src: '../../assets/items/completed/Enforcer.png',
      id: 'enforcer',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Scrap Emblem",
      description: 'The holder gains the Scrap trait.\n',
      src: '../../assets/items/completed/Scrap.png',
      id: 'scrap',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Protector Emblem",
      description: 'The holder gains the Protector trait.\n',
      src: '../../assets/items/completed/Protector.png',
      id: 'protector',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Bruiser Emblem",
      description: 'The holder gains the Bruiser trait.\n',
      src: '../../assets/items/completed/Bruiser.png',
      id: 'bruiser',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Innovator Emblem",
      description: 'The holder gains the Innovator trait.\n',
      src: '../../assets/items/completed/Innovator.png',
      id: 'innovator',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Sniper Emblem",
      description: 'The holder gains the Sniper trait.\n',
      src: '../../assets/items/completed/Sniper.png',
      id: 'sniper',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
    {
      name: "Scholar Emblem",
      description: 'The holder gains the Scholar trait.\n',
      src: '../../assets/items/completed/Scholar.png',
      id: 'scholar',
      parts: [],
      wearers: [],
      selectedAmount: 0, equippedAmount: 0,
    },
  ];

  constructor() { }

}
